config/routes.rb
Locomotive::Engine.routes.draw do

  # Authentication
  devise_for :locomotive_account,
    class_name:   'Locomotive::Account',
    skip:         [:registrations],
    path:         '',
    failure_app:  'Locomotive::Devise::FailureApp'

  devise_scope :locomotive_account do
    if Locomotive.config.enable_registration
      get     'sign_up'  => 'registrations#new',    as: :sign_up
      post    'sign_up'  => 'registrations#create'
    end
    get     'sign_in'  => 'sessions#new',         as: :sign_in
    delete  'sign_out' => 'sessions#destroy',     as: :sign_out
  end

  root to: 'sites#index'

  resources :sites

  resource :my_account, controller: 'my_account' do
    put :regenerate_api_key, on: :member
  end

  # Back-office: current site, pages, content entries, assets and the site settings
  scope ':site_handle' do

    get '/',          to: 'dashboard#show'
    get 'dashboard',  to: 'dashboard#show', as: :dashboard

    get 'developers', to: 'developers_documentation#show', as: :developers_documentation

    resources :pages do
      put :sort, on: :member
      get :get_path, on: :collection

      resource :content, controller: 'page_content', only: [:edit, :update]
      get 'content/edit/*nav', to: 'page_content#edit'
    end

    resources :editable_elements, only: [:index, :update_all], path: 'pages/:page_id/editable_elements' do
      patch :update_all, on: :collection
    end

    resources :current_site_metafields, only: [:index, :update_all] do
      patch :update_all, on: :collection
    end

    resources :accounts

    resources :memberships

    resources :translations do
      delete :bulk_destroy, on: :collection
    end

    resources :search_for_resources, only: [:index]

    resources :content_assets do
      post :bulk_create, on: :collection
    end

    resource :public_submission_accounts, only: [:edit, :update], path: 'content_types/:slug/public_submission_accounts' do
      get :new_account
    end

    resource :content_entry_import, only: [:show, :new, :create, :destroy], path: 'content_types/:slug/imports'

    resources :content_entries, path: 'content_types/:slug/entries' do
      get :show_in_form,      on: :collection
      put :sort,              on: :collection
      get :export,            on: :collection
      delete :bulk_destroy,   on: :collection      
      resource :impersonation, only: [:create], controller: 'content_entry_impersonations'
    end

    namespace :custom_fields, path: 'content_types/:slug/fields/:name' do
      resource :select_options, only: [:edit, :update] do
        get :new_option
      end
    end

    resource :current_site, controller: 'current_site' do
      get :new_domain
      get :new_locale
      get :new_url_redirection
    end

    # Preview mode handled by Steam
    mount Locomotive::Steam.to_app => '/preview', as: 'preview', anchor: false

  end
end

app/models/locomotive/account.rb
module Locomotive
  class Account

    include Locomotive::Mongoid::Document
    devise *Locomotive.config.devise_modules
    acts_as_token_authenticatable
    include Locomotive::Concerns::Account::APIKey

    ## devise fields (need to be declared since 2.x) ##
    field :remember_created_at,     type: Time
    field :email,                   type: String, default: ''
    field :encrypted_password,      type: String, default: ''
    field :authentication_token,    type: String
    field :reset_password_token,    type: String
    field :reset_password_sent_at,  type: Time
    field :password_salt,           type: String
    field :sign_in_count,           type: Integer, default: 0
    field :current_sign_in_at,      type: Time
    field :last_sign_in_at,         type: Time
    field :current_sign_in_ip,      type: String
    field :last_sign_in_ip,         type: String

    mount_uploader :avatar, PictureUploader, validate_integrity: true

    ## attributes ##
    field :name
    field :locale,  default: Locomotive.config.default_locale.to_s or 'en'
    field :super_admin, type: Boolean, default: false
    field :visitor, type: Boolean, default: false

    ## validations ##
    validates_presence_of :name
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

    ## associations ##
    has_many :created_sites, class_name: 'Locomotive::Site', validate: false, autosave: false

    ## callbacks ##
    before_destroy :remove_memberships!

    ## scopes ##
    scope :ordered,   -> { order_by(name: :asc) }
    scope :by_email,  ->(email) { where(email: email).first }

    ## indexes ##
    index({ email: 1 }, { unique: true, background: true })

    ## aliases ##
    alias_attribute :api_token, :api_key

    ## methods ##

    def sites
      @sites ||= Site.where('memberships.account_id' => self._id)
    end

    # Tell if the account has admin privileges for one (at least)
    # of his/her sites.
    #
    # @return [ Boolean ] True if admin in one of his/her sites.
    #
    def local_admin?
      Site.where(memberships: { '$elemMatch' => { account_id: self._id, role: :admin } }).count > 0
    end

    # Find the first account matching the email parameter
    #
    # @param [ String ] email The email
    #
    # @return [ Object ] The account or nil (if none)
    #
    def self.find_by_email(email)
      where(email: email).first
    end

    def devise_mailer
      Locomotive::DeviseMailer
    end

    protected

    def password_required?
      !persisted? || !password.blank? || !password_confirmation.blank?
    end

    def remove_memberships!
      self.sites.each do |site|
        membership = site.memberships.where(account_id: self._id).first

        if site.admin_memberships.size == 1 && membership.admin?
          raise ::I18n.t('errors.messages.needs_admin_account')
        else
          membership.destroy
        end
      end
    end

  end
end

app/models/locomotive/activity.rb
module Locomotive
  class Activity

    include Locomotive::Mongoid::Document

    ## fields ##
    field :key
    field :parameters,  type: Hash
    field :locale

    ## associations ##
    belongs_to :site,       class_name: 'Locomotive::Site', validate: false, autosave: false
    belongs_to :actor,      class_name: 'Locomotive::Account', validate: false, autosave: false

    ## validations ##
    validates_presence_of :key

    ## indexes ##
    index site_id: 1
    index site_id: 1, created_at: 1

    ## methods ##

    def domain
      self.key.split('.').first
    end

    def action
      self.key.split('.').last
    end

  end
end

app/models/locomotive/concerns/account/api_key.rb
module Locomotive
  module Concerns
    module Account

      # More information here: https://github.com/mongoid/mongoid/issues/3626
      module APIKey

        extend ActiveSupport::Concern

        included do

          ## fields ##
          field :api_key

          ## callbacks ##
          before_validation :api_key_should_not_be_empty

        end

        # Regenerate the API key without saving the account.
        #
        # @return [ String ] The new api key
        #
        def regenerate_api_key
          self.api_key = Digest::SHA1.hexdigest("#{self._id}-#{Time.now.to_f}-#{self.created_at}")
        end

        # Regenerate the API key AND then save the account.
        #
        def regenerate_api_key!
          self.regenerate_api_key
          self.save
        end

        private

        def api_key_should_not_be_empty
          if self.api_key.blank?
            self.regenerate_api_key
          end
        end

        module ClassMethods

          # Create the API token which will be passed to all the requests to the Locomotive API.
          # It requires the credentials of an account with admin role OR the API key of the site.
          # If an error occurs (invalid account, ...etc), this method raises an exception that has
          # to be caught somewhere.
          #
          # @param [ String ] email The email of the account
          # @param [ String ] password The password of the account
          # @param [ String ] api_key The API key of the site.
          #
          # @return [ String ] The API token
          #
          def create_api_token(email, password, api_key)
            if api_key.present?
              account = self.where(api_key: api_key).first

              raise 'The API key is invalid.' if account.nil?
            elsif email.present? && password.present?
              account = self.where(email: email.downcase).first

              raise 'Invalid email or password.' if account.nil? || !account.valid_password?(password)
            else
              raise 'The request must contain either the user email and password OR the API key.'
            end

            account.ensure_authentication_token
            account.save

            account.authentication_token
          end

          # Logout the user responding to the token passed in parameter from the API.
          # An exception is raised if no account corresponds to the token.
          #
          # @param [ String ] token The API token created by the create_api_token method.
          #
          # @return [ String ] The API token
          #
          def invalidate_api_token(token)
            account = self.where(authentication_token: token).first

            raise 'Invalid token.' if account.nil?

            account.reset_authentication_token!

            token
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/asset/checksum.rb
module Locomotive
  module Concerns
    module Asset

      module Checksum

        extend ActiveSupport::Concern

        included do
          ## fields ##
          field :checksum

          ## callbacks ##
          before_save :calculate_checksum
        end

        private

        def calculate_checksum
          begin
            self.checksum = Digest::MD5.hexdigest(self.source.read)
          rescue Errno::ENOENT => e
            # no file
          end
        end

      end

    end
  end
end

app/models/locomotive/concerns/asset/types.rb
module Locomotive
  module Concerns
    module Asset
      module Types

        extend ActiveSupport::Concern

        included do
          scope :by_content_type,   ->(content_type)  { content_type.blank? ? all : where(content_type: content_type.to_s) }
          scope :by_content_types,  ->(content_types) { content_types.blank? ? all : where(:content_type.in => [*content_types]) }

          all_types.each do |type|
            scope :"only_#{type}", -> { where(content_type: type) }

            define_method("#{type}?") do
              self.content_type.to_s == type
            end
          end
        end

        module ClassMethods

          def all_types
            %w{image pdf media stylesheet javascript font}
          end

          def types_for_content_editing
            all_types - %w(stylesheet javascript font)
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/asset/vignette.rb
module Locomotive
  module Concerns
    module Asset
      module Vignette

        def vignette_url
          if self.image?
            # In some case (like an invalid extension) the height, width can be nill
            # In that case we should directly return the url
            if self.width && self.height && self.width < 85 && self.height < 85
              self.source.url
            else
              Locomotive::Dragonfly.resize_url(self.source, '85x85#', self.updated_at.to_i)
            end
          elsif self.pdf?
            Locomotive::Dragonfly.thumbnail_pdf(self.source, '85x85#', self.updated_at.to_i)
          end
        end

        def alternative_vignette_url
          format = if self.image? && self.width && self.height
            '190x120>'
          elsif self.pdf?
            '190x120#'
          end

          Locomotive::Dragonfly.thumbnail_pdf(self.source, format, self.updated_at.to_i) if format
        end

        def big_vignette_url
          format = if self.image? || self.pdf?
            '200x200#'
          end

          Locomotive::Dragonfly.thumbnail_pdf(self.source, format, self.updated_at.to_i) if format
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/authentication.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Authentication

        def with_authentication?
          self.content_type.entries_custom_fields.where(type: 'password').count > 0
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/counter.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Counter

        extend ActiveSupport::Concern

        included do

          ## callbacks ##
          after_create  :inc_number_of_entries
          after_destroy :dec_number_of_entries

        end

        private

        def inc_number_of_entries
          change_number_of_entries(1)
        end

        def dec_number_of_entries
          change_number_of_entries(-1)
        end

        def change_number_of_entries(delta)
          Locomotive::ContentType.collection.update_one(
            { _id: self.content_type_id },
            {
              '$inc' => { 'number_of_entries' => delta },
              '$set' => { 'updated_at' => Time.zone.now }
            })
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/csv.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Csv

        extend ActiveSupport::Concern

        # Get the values from the custom fields as an array.
        # Values are ordered by the position of the custom fields.
        # It also adds the created_at value of the instance.
        #
        # @param [ Hash ] options For now, stores only the host for the File fields.
        #
        # @return [ Array ]
        #
        def to_values(options = {})
          values = self.content_type.ordered_entries_custom_fields.map do |field|
            value = self.send(field.name)
            self.value_from_type(field.type.to_sym, value, options)
          end.compact

          values << I18n.l(self.created_at, format: :long)
        end

        protected

        # Return the transformed value for a particular field type (string, text, ...etc).
        #
        # @param [ Symbol ] type Type of the field
        # @param [ Object ] value Value of the field in the current instance
        # @param [ Hash ] options For now, stores only the host for the File fields.
        #
        # @return [ Object ]
        #
        def value_from_type(type, value, options)
          case type
          when :file
            value.blank? ? '' : value.guess_url(options[:host])
          when :belongs_to
            value.try(:_label) || ''
          when :has_many, :many_to_many
            value.map(&:_label).join(', ')
          when :tags
            [*value].join(', ')
          else
            value == nil ? '' : value
          end
        end

        module ClassMethods

          # Generate a csv from a collection of content entries
          #
          # @param [ Hash ] options Options for the csv generation
          #
          # @return [ String ] The well-generated CSV document
          #
          def to_csv(options = {})
            # puts "to_csv #{all.count.inspect} / #{all.first.inspect}"
            # puts "#{all.first.content_type_id.inspect}"
            # puts "#{all.first.content_type.inspect}"
            # binding.pry
            content_type  = options.delete(:content_type) || all.first.try(:content_type)
            csv_options   = options.select do |k, v|
              CSV::DEFAULT_OPTIONS.keys.include?(k.to_sym)
            end

            fields = content_type.ordered_entries_custom_fields
            labels = fields.map(&:label) << I18n.t('mongoid.attributes.locomotive/content_entry.created_at')

            CSV.generate(**csv_options) do |csv|
              # header
              csv << labels
              # body
              all.each_by(100) do |entry|
                csv << entry.to_values(options)
              end
            end
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/file_size.rb
module Locomotive
  module Concerns
    module ContentEntry
      module FileSize

        extend ActiveSupport::Concern

        included do

          ## fields ##
          field :_file_size, type: Integer, default: 0

          ## callbacks ##
          before_save :sync_file_size

        end

        private

        def sync_file_size
          self._file_size = self.file_custom_fields.inject(0) do |sum, field|
            file = send(field)&.file
            _size = file&.exists? ? file.size : 0
            _size + sum
          end
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_type/filter_fields.rb
module Locomotive
  module Concerns
    module ContentType
      module FilterFields

        extend ActiveSupport::Concern

        included do
          ## fields ##
          field :filter_fields, type: Array

          ## callbacks ##
          before_validation :sanitize_filter_fields
        end

        # We do not want to have a blank value in the list of fields used to filter the entries.
        def sanitize_filter_fields
          if self.filter_fields
            self.filter_fields.reject! { |id| id.blank? }
          end
        end

      end
    end
  end
end

app/views/locomotive/content_assets/_dropzone.html.slim
.instructions
  i.fas.fa-cloud-upload-alt
  br
  = t('.instructions').html_safe
  | &nbsp;
  = link_to t('.browse'), '#', class: 'upload'
  br
  br
  i
    = t('.maximum_file_size', maximum: number_to_human_size(current_site.maximum_uploaded_file_size)).html_safe

= form_tag('', class: 'hide') do
  = file_field_tag :source, multiple: true

= link_to 'Refresh', request.fullpath, remote: remote, class: 'refresh hide'

.progress.hide
  .progress-bar role='progressbar' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100'

app/views/locomotive/content_assets/_list.html.slim
- if @content_assets.empty?
  br

  .alert.alert-warning
    == t('.no_items')

- else
  - # Display the assets
  .content-assets-list
    - @content_assets.each do |asset|
      .asset
        .top
          h2= asset_filename(asset)
          .size= human_asset_size(asset)

        .body
          .small-thumbnail
            - if asset_with_thumbnail?(asset) && thumbnail_url = asset.alternative_vignette_url
              = image_tag thumbnail_url
            - else
              div class="not-a-image #{asset.content_type}"
                span= asset_text(asset)

        .actions
          - if asset.source&.url
            = link_to asset.source.url, class: 'btn btn-primary btn-sm', target: '_blank' do
              i.fas.fa-download
            | &nbsp;

          - if enable_select
            = link_to t('.buttons.select'), asset.source.url, class: 'btn btn-primary btn-sm select', title: asset_filename(asset), data: { image: asset.image? }
            | &nbsp;

          - if asset.image?
            = link_to t('.buttons.edit'), edit_content_asset_path(current_site, asset._id), class: 'btn btn-primary btn-sm edit'

          | &nbsp;&nbsp;

          = link_to content_asset_path(current_site, asset, params.to_unsafe_h.slice(:types, :query, :page, :per_page)), class: 'remove', method: :delete, data: { confirm: t('locomotive.messages.confirm'), return_url: request.original_url }, title: t(:delete, scope: 'simple_form.buttons.defaults.locomotive'), remote: remote do
            i.far.fa-trash-alt

  .text-center
    = paginate @content_assets, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-sm', remote: remote

app/views/locomotive/content_assets/_nav.html.slim
- # Filter assets
ul.nav.nav-tabs  role='tablist'
  li class="#{'active' if params[:types].nil? }"
    = link_to t('.types.all'), content_assets_path(current_site, query: params[:query]), remote: remote

  - Locomotive::ContentAsset.types_for_content_editing.each do |type|
    li class="#{'active' if params[:types] == type }"
      = link_to t(".types.#{type}"), content_assets_path(current_site, types: type, query: params[:query]), remote: remote
  li class="#{'active' if params[:types] == 'other' }"
    = link_to t('.types.others'), content_assets_path(current_site, types: 'other', query: params[:query]), remote: remote

  li.search-bar.search-bar-in-nav.visible-md-block.visible-lg-block
    = render 'search_form', remote: remote

.search-bar.search-bar-in-nav.visible-xs-block.visible-sm-block
  = render 'search_form', remote: remote

app/views/locomotive/content_assets/_search_form.html.slim
= form_tag content_assets_path(current_site), method: 'GET', remote: remote do
  = hidden_field_tag :types, params[:types] if params[:types]
  .form-group
    i.fa.fa-search.icon
    = text_field_tag :query, params[:query], placeholder: t('.placeholder'), class: 'form-control'

app/views/locomotive/content_assets/edit_in_drawer.html.slim
.edit-assets-container
  .image-container data-height=@content_asset.height data-width=@content_asset.width data-filename=@content_asset.name

    = image_tag @content_asset.source.url

  .resize-form style='display: none'
    - resize_form = image_resize_form(@content_asset)
    = locomotive_form_for resize_form, url: '#' do |f|
      = f.inputs do
        = f.input :width
        = f.input :height

      .text-right
        button.btn.btn-sm.btn-success.apply-resizing-btn autocomplete='off' data-loading-text=f.submit_text(:loading_text)
          = f.submit_text
        | &nbsp;
        button.btn.btn-sm.btn-default.cancel-resizing-btn autocomplete="off"
          = f.submit_text :cancel

  .actions
    .btn-group-vertical role="group"
      button.btn.btn-sm.btn-primary.resize-btn title=t('.buttons.resize')
        i.fa.fa-compress
      button.btn.btn-sm.btn-primary.crop-btn  title=t('.buttons.crop')
        i.fa.fa-crop
      button.btn.btn-sm.btn-success.apply-btn title=t('.buttons.apply') data-url=content_assets_path(current_site, format: :json)
        i.fa.fa-check

app/views/locomotive/content_assets/index.html.slim
.content-assets  data-refresh-url=content_assets_path(current_site)
  .row
    .col-md-9.col-xs-12.col-sm-12
      .row.header-row
        .col-md-8.col-xs-9
          h1== t('.title')
        .col-md-4.col-xs-3.actions
          .visible-xs-block.visible-sm-block
            p.text-right
              = link_to t('.upload'), bulk_create_content_assets_path(current_site, :json), class: 'btn btn-sm btn-primary upload'

      .nav-container
        = render 'nav', remote: false

      = render 'list', remote: false, enable_select: false

    .col-md-3.dropzone.sidebar-dropzone.hidden-xs.hidden-sm data-url= bulk_create_content_assets_path(current_site, :json)
      .dropzone-inner
        = render 'dropzone', remote: false

app/views/locomotive/content_assets/index_in_drawer.html.slim
.content-assets

  .dropzone.top-dropzone data-url=bulk_create_content_assets_path(current_site, :json)
    .container-fluid
      .row
        .col-md-12
          = render 'dropzone', remote: true

  .updatable
    .nav-container
      .container-fluid
        .row
          .col-md-12
            = render 'nav', remote: true

    .list-container.scrollable
      .container-fluid
        .row
          .col-md-12
            = render 'list', remote: true, enable_select: true