config/routes.rb
Locomotive::Engine.routes.draw do

  # Authentication
  devise_for :locomotive_account,
    class_name:   'Locomotive::Account',
    skip:         [:registrations],
    path:         '',
    failure_app:  'Locomotive::Devise::FailureApp'

  devise_scope :locomotive_account do
    if Locomotive.config.enable_registration
      get     'sign_up'  => 'registrations#new',    as: :sign_up
      post    'sign_up'  => 'registrations#create'
    end
    get     'sign_in'  => 'sessions#new',         as: :sign_in
    delete  'sign_out' => 'sessions#destroy',     as: :sign_out
  end

  root to: 'sites#index'

  resources :sites

  resource :my_account, controller: 'my_account' do
    put :regenerate_api_key, on: :member
  end

  # Back-office: current site, pages, content entries, assets and the site settings
  scope ':site_handle' do

    get '/',          to: 'dashboard#show'
    get 'dashboard',  to: 'dashboard#show', as: :dashboard

    get 'developers', to: 'developers_documentation#show', as: :developers_documentation

    resources :pages do
      put :sort, on: :member
      get :get_path, on: :collection

      resource :content, controller: 'page_content', only: [:edit, :update]
      get 'content/edit/*nav', to: 'page_content#edit'
    end

    resources :editable_elements, only: [:index, :update_all], path: 'pages/:page_id/editable_elements' do
      patch :update_all, on: :collection
    end

    resources :current_site_metafields, only: [:index, :update_all] do
      patch :update_all, on: :collection
    end

    resources :accounts

    resources :memberships

    resources :translations do
      delete :bulk_destroy, on: :collection
    end

    resources :search_for_resources, only: [:index]

    resources :content_assets do
      post :bulk_create, on: :collection
    end

    resource :public_submission_accounts, only: [:edit, :update], path: 'content_types/:slug/public_submission_accounts' do
      get :new_account
    end

    resource :content_entry_import, only: [:show, :new, :create, :destroy], path: 'content_types/:slug/imports'

    resources :content_entries, path: 'content_types/:slug/entries' do
      get :show_in_form,      on: :collection
      put :sort,              on: :collection
      get :export,            on: :collection
      delete :bulk_destroy,   on: :collection      
      resource :impersonation, only: [:create], controller: 'content_entry_impersonations'
    end

    namespace :custom_fields, path: 'content_types/:slug/fields/:name' do
      resource :select_options, only: [:edit, :update] do
        get :new_option
      end
    end

    resource :current_site, controller: 'current_site' do
      get :new_domain
      get :new_locale
      get :new_url_redirection
    end

    # Preview mode handled by Steam
    mount Locomotive::Steam.to_app => '/preview', as: 'preview', anchor: false

  end
end

app/models/locomotive/account.rb
module Locomotive
  class Account

    include Locomotive::Mongoid::Document
    devise *Locomotive.config.devise_modules
    acts_as_token_authenticatable
    include Locomotive::Concerns::Account::APIKey

    ## devise fields (need to be declared since 2.x) ##
    field :remember_created_at,     type: Time
    field :email,                   type: String, default: ''
    field :encrypted_password,      type: String, default: ''
    field :authentication_token,    type: String
    field :reset_password_token,    type: String
    field :reset_password_sent_at,  type: Time
    field :password_salt,           type: String
    field :sign_in_count,           type: Integer, default: 0
    field :current_sign_in_at,      type: Time
    field :last_sign_in_at,         type: Time
    field :current_sign_in_ip,      type: String
    field :last_sign_in_ip,         type: String

    mount_uploader :avatar, PictureUploader, validate_integrity: true

    ## attributes ##
    field :name
    field :locale,  default: Locomotive.config.default_locale.to_s or 'en'
    field :super_admin, type: Boolean, default: false
    field :visitor, type: Boolean, default: false

    ## validations ##
    validates_presence_of :name
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

    ## associations ##
    has_many :created_sites, class_name: 'Locomotive::Site', validate: false, autosave: false

    ## callbacks ##
    before_destroy :remove_memberships!

    ## scopes ##
    scope :ordered,   -> { order_by(name: :asc) }
    scope :by_email,  ->(email) { where(email: email).first }

    ## indexes ##
    index({ email: 1 }, { unique: true, background: true })

    ## aliases ##
    alias_attribute :api_token, :api_key

    ## methods ##

    def sites
      @sites ||= Site.where('memberships.account_id' => self._id)
    end

    # Tell if the account has admin privileges for one (at least)
    # of his/her sites.
    #
    # @return [ Boolean ] True if admin in one of his/her sites.
    #
    def local_admin?
      Site.where(memberships: { '$elemMatch' => { account_id: self._id, role: :admin } }).count > 0
    end

    # Find the first account matching the email parameter
    #
    # @param [ String ] email The email
    #
    # @return [ Object ] The account or nil (if none)
    #
    def self.find_by_email(email)
      where(email: email).first
    end

    def devise_mailer
      Locomotive::DeviseMailer
    end

    protected

    def password_required?
      !persisted? || !password.blank? || !password_confirmation.blank?
    end

    def remove_memberships!
      self.sites.each do |site|
        membership = site.memberships.where(account_id: self._id).first

        if site.admin_memberships.size == 1 && membership.admin?
          raise ::I18n.t('errors.messages.needs_admin_account')
        else
          membership.destroy
        end
      end
    end

  end
end

app/models/locomotive/activity.rb
module Locomotive
  class Activity

    include Locomotive::Mongoid::Document

    ## fields ##
    field :key
    field :parameters,  type: Hash
    field :locale

    ## associations ##
    belongs_to :site,       class_name: 'Locomotive::Site', validate: false, autosave: false
    belongs_to :actor,      class_name: 'Locomotive::Account', validate: false, autosave: false

    ## validations ##
    validates_presence_of :key

    ## indexes ##
    index site_id: 1
    index site_id: 1, created_at: 1

    ## methods ##

    def domain
      self.key.split('.').first
    end

    def action
      self.key.split('.').last
    end

  end
end

app/models/locomotive/concerns/account/api_key.rb
module Locomotive
  module Concerns
    module Account

      # More information here: https://github.com/mongoid/mongoid/issues/3626
      module APIKey

        extend ActiveSupport::Concern

        included do

          ## fields ##
          field :api_key

          ## callbacks ##
          before_validation :api_key_should_not_be_empty

        end

        # Regenerate the API key without saving the account.
        #
        # @return [ String ] The new api key
        #
        def regenerate_api_key
          self.api_key = Digest::SHA1.hexdigest("#{self._id}-#{Time.now.to_f}-#{self.created_at}")
        end

        # Regenerate the API key AND then save the account.
        #
        def regenerate_api_key!
          self.regenerate_api_key
          self.save
        end

        private

        def api_key_should_not_be_empty
          if self.api_key.blank?
            self.regenerate_api_key
          end
        end

        module ClassMethods

          # Create the API token which will be passed to all the requests to the Locomotive API.
          # It requires the credentials of an account with admin role OR the API key of the site.
          # If an error occurs (invalid account, ...etc), this method raises an exception that has
          # to be caught somewhere.
          #
          # @param [ String ] email The email of the account
          # @param [ String ] password The password of the account
          # @param [ String ] api_key The API key of the site.
          #
          # @return [ String ] The API token
          #
          def create_api_token(email, password, api_key)
            if api_key.present?
              account = self.where(api_key: api_key).first

              raise 'The API key is invalid.' if account.nil?
            elsif email.present? && password.present?
              account = self.where(email: email.downcase).first

              raise 'Invalid email or password.' if account.nil? || !account.valid_password?(password)
            else
              raise 'The request must contain either the user email and password OR the API key.'
            end

            account.ensure_authentication_token
            account.save

            account.authentication_token
          end

          # Logout the user responding to the token passed in parameter from the API.
          # An exception is raised if no account corresponds to the token.
          #
          # @param [ String ] token The API token created by the create_api_token method.
          #
          # @return [ String ] The API token
          #
          def invalidate_api_token(token)
            account = self.where(authentication_token: token).first

            raise 'Invalid token.' if account.nil?

            account.reset_authentication_token!

            token
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/asset/checksum.rb
module Locomotive
  module Concerns
    module Asset

      module Checksum

        extend ActiveSupport::Concern

        included do
          ## fields ##
          field :checksum

          ## callbacks ##
          before_save :calculate_checksum
        end

        private

        def calculate_checksum
          begin
            self.checksum = Digest::MD5.hexdigest(self.source.read)
          rescue Errno::ENOENT => e
            # no file
          end
        end

      end

    end
  end
end

app/models/locomotive/concerns/asset/types.rb
module Locomotive
  module Concerns
    module Asset
      module Types

        extend ActiveSupport::Concern

        included do
          scope :by_content_type,   ->(content_type)  { content_type.blank? ? all : where(content_type: content_type.to_s) }
          scope :by_content_types,  ->(content_types) { content_types.blank? ? all : where(:content_type.in => [*content_types]) }

          all_types.each do |type|
            scope :"only_#{type}", -> { where(content_type: type) }

            define_method("#{type}?") do
              self.content_type.to_s == type
            end
          end
        end

        module ClassMethods

          def all_types
            %w{image pdf media stylesheet javascript font}
          end

          def types_for_content_editing
            all_types - %w(stylesheet javascript font)
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/asset/vignette.rb
module Locomotive
  module Concerns
    module Asset
      module Vignette

        def vignette_url
          if self.image?
            # In some case (like an invalid extension) the height, width can be nill
            # In that case we should directly return the url
            if self.width && self.height && self.width < 85 && self.height < 85
              self.source.url
            else
              Locomotive::Dragonfly.resize_url(self.source, '85x85#', self.updated_at.to_i)
            end
          elsif self.pdf?
            Locomotive::Dragonfly.thumbnail_pdf(self.source, '85x85#', self.updated_at.to_i)
          end
        end

        def alternative_vignette_url
          format = if self.image? && self.width && self.height
            '190x120>'
          elsif self.pdf?
            '190x120#'
          end

          Locomotive::Dragonfly.thumbnail_pdf(self.source, format, self.updated_at.to_i) if format
        end

        def big_vignette_url
          format = if self.image? || self.pdf?
            '200x200#'
          end

          Locomotive::Dragonfly.thumbnail_pdf(self.source, format, self.updated_at.to_i) if format
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/authentication.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Authentication

        def with_authentication?
          self.content_type.entries_custom_fields.where(type: 'password').count > 0
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/counter.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Counter

        extend ActiveSupport::Concern

        included do

          ## callbacks ##
          after_create  :inc_number_of_entries
          after_destroy :dec_number_of_entries

        end

        private

        def inc_number_of_entries
          change_number_of_entries(1)
        end

        def dec_number_of_entries
          change_number_of_entries(-1)
        end

        def change_number_of_entries(delta)
          Locomotive::ContentType.collection.update_one(
            { _id: self.content_type_id },
            {
              '$inc' => { 'number_of_entries' => delta },
              '$set' => { 'updated_at' => Time.zone.now }
            })
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/csv.rb
module Locomotive
  module Concerns
    module ContentEntry
      module Csv

        extend ActiveSupport::Concern

        # Get the values from the custom fields as an array.
        # Values are ordered by the position of the custom fields.
        # It also adds the created_at value of the instance.
        #
        # @param [ Hash ] options For now, stores only the host for the File fields.
        #
        # @return [ Array ]
        #
        def to_values(options = {})
          values = self.content_type.ordered_entries_custom_fields.map do |field|
            value = self.send(field.name)
            self.value_from_type(field.type.to_sym, value, options)
          end.compact

          values << I18n.l(self.created_at, format: :long)
        end

        protected

        # Return the transformed value for a particular field type (string, text, ...etc).
        #
        # @param [ Symbol ] type Type of the field
        # @param [ Object ] value Value of the field in the current instance
        # @param [ Hash ] options For now, stores only the host for the File fields.
        #
        # @return [ Object ]
        #
        def value_from_type(type, value, options)
          case type
          when :file
            value.blank? ? '' : value.guess_url(options[:host])
          when :belongs_to
            value.try(:_label) || ''
          when :has_many, :many_to_many
            value.map(&:_label).join(', ')
          when :tags
            [*value].join(', ')
          else
            value == nil ? '' : value
          end
        end

        module ClassMethods

          # Generate a csv from a collection of content entries
          #
          # @param [ Hash ] options Options for the csv generation
          #
          # @return [ String ] The well-generated CSV document
          #
          def to_csv(options = {})
            # puts "to_csv #{all.count.inspect} / #{all.first.inspect}"
            # puts "#{all.first.content_type_id.inspect}"
            # puts "#{all.first.content_type.inspect}"
            # binding.pry
            content_type  = options.delete(:content_type) || all.first.try(:content_type)
            csv_options   = options.select do |k, v|
              CSV::DEFAULT_OPTIONS.keys.include?(k.to_sym)
            end

            fields = content_type.ordered_entries_custom_fields
            labels = fields.map(&:label) << I18n.t('mongoid.attributes.locomotive/content_entry.created_at')

            CSV.generate(**csv_options) do |csv|
              # header
              csv << labels
              # body
              all.each_by(100) do |entry|
                csv << entry.to_values(options)
              end
            end
          end

        end

      end
    end
  end
end

app/models/locomotive/concerns/content_entry/file_size.rb
module Locomotive
  module Concerns
    module ContentEntry
      module FileSize

        extend ActiveSupport::Concern

        included do

          ## fields ##
          field :_file_size, type: Integer, default: 0

          ## callbacks ##
          before_save :sync_file_size

        end

        private

        def sync_file_size
          self._file_size = self.file_custom_fields.inject(0) do |sum, field|
            file = send(field)&.file
            _size = file&.exists? ? file.size : 0
            _size + sum
          end
        end

      end
    end
  end
end

app/models/locomotive/concerns/content_type/filter_fields.rb
module Locomotive
  module Concerns
    module ContentType
      module FilterFields

        extend ActiveSupport::Concern

        included do
          ## fields ##
          field :filter_fields, type: Array

          ## callbacks ##
          before_validation :sanitize_filter_fields
        end

        # We do not want to have a blank value in the list of fields used to filter the entries.
        def sanitize_filter_fields
          if self.filter_fields
            self.filter_fields.reject! { |id| id.blank? }
          end
        end

      end
    end
  end
end

app/views/locomotive/shared/_account_navigation.slim
nav.navigation class="#{class_name rescue ''}"
  = link_to root_path, class: 'brand-logo' do
    = account_logo_tag

  = render 'locomotive/shared/account/navigation'

app/views/locomotive/shared/_head.html.slim
- if current_site
  title== escape_once("#{current_site.name} &mdash; #{Locomotive.config.name}")
- else
  title= escape_once(Locomotive.config.name)

= csrf_meta_tag

- key = Rails.application.config.session_options[:key]

meta name='key-param' content=Rails.application.config.session_options[:key]
meta name='key-token' content=cookies[key]
meta name='unsaved-content-warning' content=t('locomotive.messages.unsaved_content_warning')
meta name="viewport" content="width=device-width, initial-scale=1"

link rel="icon" type="image/png" href="#{asset_url('locomotive/favicon.png')}" sizes="32x32"

javascript:
  window.Locomotive = { mounted_on: '#{Locomotive.mounted_on}' }

link href="https://fonts.googleapis.com/css?family=Muli:400,300|Noto+Sans:400,700" rel="stylesheet" type="text/css"

= stylesheet_link_tag     'locomotive/application', media: 'screen'
= javascript_include_tag  'locomotive'

= render 'locomotive/shared/main_app_head_before_backbone'

javascript:
  window.locale                     = '#{locale}';
  window.content_locale             = '#{current_content_locale}';

  $(document).ready(function() {

    window.application_view = new Locomotive.Views.ApplicationView({
      flash:      #{{flash_messages_to_json}},
      view:       #{backbone_view_class_name}
    });
    window.application_view.render();

  });

= yield :head

= render 'locomotive/shared/main_app_head'

app/views/locomotive/shared/_locale_picker_link.html.slim
.btn-group.locale-picker-btn-group
  button.btn.btn-primary.btn-sm.dropdown-toggle data-toggle='dropdown' data-aria-haspopup='true' data-aria-expanded='false'
    = flag_tag current_content_locale, '17x17'
    | &nbsp;
    | &nbsp;
    span.caret
  ul.dropdown-menu.dropdown-menu-right
    - current_site.locales.each do |locale|
      - url = url_block ? url_block.call(locale) : "?content_locale=#{locale}"
      li
        a href=url
          = flag_tag locale, '17x17'
          | &nbsp;
          | &nbsp;
          = t(locale, scope: 'locomotive.locales')

app/views/locomotive/shared/_main_app_head.html.slim
- # this partial can be overridden in the main app in order to include extra css or js

app/views/locomotive/shared/_main_app_head_before_backbone.html.slim
- # this partial can be overridden in the main app in order to include extra js before Backbone is initialized to include your own backbone Views/Models when extending the backoffice with your custom views.

app/views/locomotive/shared/_main_app_header.html.slim
- # this partial can be overridden in the main app in order to include a warning message for instance

app/views/locomotive/shared/_navigation.html.slim
nav.navigation.navigation-app
  .navigation-trigger
    .fa.fa-caret-left
    .fa.fa-bars
    .fa.fa-caret-right

  - if (_title = yield(:site_title)).present?
    .navigation-middle
      = _title
  - else
    .navigation-middle
      = link_to current_site.name_was, dashboard_path(current_site)

      - if with_preview_link
        = link_to preview_path(current_site), target: 'blank' do
          i.fas.fa-external-link-alt

  = render 'locomotive/shared/account/navigation'

  = render 'locomotive/shared/main_app_header'

app/views/locomotive/shared/_sidebar.html.slim
.sidebar role="tablist" aria-multiselectable="false" data-current-section=sidebar_current_section_class
  = link_to root_path, class: 'sidebar-logo' do
    = sidebar_logo_tag

  - cache(cache_key_for_sidebar) do
    = link_to dashboard_path(current_site), class: sidebar_link_class(:dashboard) do
      i.fa.fa-chart-bar
      span= t('.dashboard')

    - cache(cache_key_for_sidebar_pages) do
      = link_to '#collapsePages', data: { toggle: 'collapse' }, aria: { expanded: 'false', controls: 'collapsePages' }, class: sidebar_link_class(:pages) do
        i.far.fa-file-alt
        span= t('.pages')
        i.fa.fa-caret-down

      = render_pages

    - cache(cache_key_for_sidebar_content_types) do
      = render 'locomotive/shared/sidebar/content_types'

    = link_to content_assets_path(current_site), class: sidebar_link_class(:content_assets) do
      i.far.fa-images
      span= t('.assets')

    - if current_site.translations.count > 0
      = link_to translations_path(current_site), class: sidebar_link_class(:translations) do
        i.fa.fa-globe
        span= t('.translations')

    - if current_site.has_metafields?
      = link_to current_site_metafields_path(current_site), class: sidebar_link_class(:current_site_metafields) do
        i.fa class=current_site_metafields_ui[:icon]
        span= current_site_metafields_ui[:label]

    = link_to edit_current_site_path(current_site), class: sidebar_link_class(:current_site) do
      i.fas.fa-cogs
      span= t('.settings')

    - if policy(current_site).show_developers_documentation?
      = link_to developers_documentation_path(current_site), class: sidebar_link_class(:developers_documentation) do
        i.far.fa-file-code
        span= t('.developers')